### ISSUE TITLE
Add illustration of MLOps vs ML model

### ISSUE THREAD

**Issue by rmarquis** [swiss-ai-center/a-guide-to-mlops#144]
Add an illustration that put MLOps in perspective vs ML model, since the latter is well known while MLOps lifecycle is much more abstract for newcomers.

The idea is to show visually that ML models are a tiny part of the ML field, compared to all the process required for production.
(for inspiration, look for example at Andrew Ng's courses).

**Comment by ludelafo** [comment]
I guess these diagrams could be used in the presentation as well to illustrate the differences.

**Comment by rmarquis** [comment]
![Screenshot 2024-03-06 140621](https://github.com/swiss-ai-center/a-guide-to-mlops/assets/162442/470f0ccf-e28f-449f-ba76-94e51637803a)

This is the picture I had in mind, as I saw it referenced in some high profile ML courses.
Taken from [D. Sculley et. al. NIPS 2015: Hidden technical debt in Machine learning systems](https://dl.acm.org/doi/10.5555/2969442.2969519). A copy of the PDF can be found [here](https://proceedings.neurips.cc/paper/2015/file/86df7dcfd896fcaf2674f757a2463eba-Paper.pdf).
