### ISSUE TITLE
Workflow actions need version update

### ISSUE THREAD

**Issue by rmarquis** [swiss-ai-center/a-guide-to-mlops#145]
When running workflow on GitHub action:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, google-github-actions/auth@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

A simple version bump should be sufficient here. Adjust the guide content accordingly.

TODO:
- [x] actions version bumps (checkout@v4, actions/setup-python@v5, google-github-actions/auth@v2)
- [x] node version 16 -> 20 (fo CML report for example)
- [x] CML setup: iterative/setup-cml@v2

**Comment by ludelafo** [comment]
Fixed in #138.
