### ISSUE TITLE
Add a license on this work?

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/a-guide-to-mlops#153]
Should we add a license on this work?

I have experience with Creative Commons licenses (https://creativecommons.org/licenses/by-sa/4.0/) but maybe it is not what we want/need.

The following chooser can help use the right licence: <https://chooser-beta.creativecommons.org/>.

**Comment by rmarquis** [comment]
Don't we use the CC-BY-SA-4.0 license already? See [LICENSE](https://github.com/swiss-ai-center/a-guide-to-mlops/blob/main/LICENSE) file. Or maybe you think about adding the license visible directly  in the guide?

I'd consider the CC-BY-SA the perfect choice for FOSS documentation.

**Comment by ludelafo** [comment]
You're right! I'll open my eyes next time and close this issue then. 🙃
