### ISSUE TITLE
Make usage of DVCLive

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/a-guide-to-mlops#76]

**Comment by ludelafo** [comment]
@rmarquis, do you remember the use-case of DVCLive? Should we close this issue?

**Comment by rmarquis** [comment]
If I remember correctly, DVCLive added an interface to track computation and current state of the metrics, a bit like Tensorboard.
I've always felt the dependency toward DVCLive was a bit "too much" (it's geared towards getting users to buy iterative Studio), and TensorBoard is more likely to be used in the industry as a "de-factor" standard tool for vizualization.

Closing now.
